
// This file was generated by Prisma and assumes you have installed the following:
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

/**
 * prisma.config.ts	DIRECT_URL	5432 (session pooler)	Prisma CLI only — migrate deploy, db push, Studio: - when deployed to supabase
 *  */ 

export default defineConfig({
  // schema: "prisma/schema.prisma", // single file schema
  schema: "prisma/schema", // running multiple schemas
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DIRECT_URL"),
  },
});
